version: '3.9'

services:

  db:
    container_name: db
    platform: linux/amd64
    image: postgres:15.2-alpine
    ports:
      - "54322:5432"
    restart: always
    env_file: './pgsql/local/.env.local'
    volumes:
      - project-pgsql-data:/var/lib/postgresql/data
    networks:
      - project-net

  backend:
    container_name: backend
    build:
      context: ./backend
      args:
        - DEV=true
    tty: true
    ports:
      - "8000:8000"
    restart: unless-stopped
    working_dir: /app
    env_file: './backend/.env.local'
    environment:
      CONTAINER_ROLE: app
      CONTAINER_ENV: local
    volumes:
      - ./backend:/app
    depends_on:
      - db
    networks:
      - project-net

  project-redis:
    image: redis:6.2-alpine
    container_name: project-redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redisdata:/data
    networks:
      - project-net

  project-celery:
    container_name: project-celery
    build:
      context: ./backend
      args:
        - DEV=true
    command: celery -A app worker -l info
    tty: true
    restart: unless-stopped
    working_dir: /app
    env_file: './backend/.env.local'
    volumes:
      - ./backend:/app
    depends_on:
      - backend
      - db
      - project-redis
    networks:
      - project-net

volumes:
  project-pgsql-data:
  redisdata:

networks:
  project-net:
    driver: bridge


