# Generated by Django 4.1.6 on 2024-01-04 22:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0005_order_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.SmallIntegerField(
                choices=[(0, "Pending"), (1, "Checked")], default=0
            ),
        ),
    ]
