# Generated by Django 4.2 on 2024-01-05 21:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0007_order_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
