# Generated by Django 4.2 on 2024-01-05 22:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0008_product_stock"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("product", "cart")},
        ),
    ]
