from .product_list_view import product_list_view
from .product_detail_view import product_detail_view
from .client.user_add_to_cart_view import user_add_to_cart_view
from .client.user_cart_list_view import user_cart_list_view
from .client.user_make_order_view import user_make_order_view
from .client.user_order_list_view import user_order_list_view
from .client.user_cart_quantity_decrease_view import user_decrease_cart_quantity_view
from .sale.user_create_product_view import product_create_view
